### ISSUE TITLE
help on the fixed rate ward contract

### ISSUE THREAD

**Issue by nzarambaelisa** [jamesbachini/Solidity-Snippets#1]

**Comment by jamesbachini** [comment]
You would want to get it audited or at least do some good unit testing before deploying any of these contracts if they are going to be used for user funds.

Unstake (withdraw) actually claims as well here on line28:
https://github.com/jamesbachini/Solidity-Snippets/blob/30474ff7e0ab9ca0e3db5856e6472e31f10234a7/contracts/FixedRateStaking.sol#L28

This gives the user two options to either unstake and claim all rewards or to just claim the rewards and leave the collateral staked.

**Comment by nzarambaelisa** [comment]
i tried compiling the contract in remix, and i was given an error for the line "claim();". but where i have a question mostly is on the part, on your website, where you said that to complete the contract, we should add a function to stakeAll() so that the initial deposit and rewards can be withdrew together. can you write me the function?

here is the form of my contract

```solidity 
// SPDX-License-Identifier: MIT
pragma solidity >=0.8.7;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/utils/math/SafeMath.sol";

error TransferFailed();

contract FixedStaking {
    using SafeMath for uint;
    mapping(address => uint) public staked;
    mapping(address => uint) private stakedFromTS;
    IERC20 public USDC;
    
    

    event Staked(address indexed user, uint256 indexed amount);
    event WithdrewStake(address indexed user, uint256 indexed amount);



     constructor(address _USDC) {
         USDC = IERC20(_USDC); 
         
        //0x5425890298aed601595a70AB815c96711a31Bc65
        //0x5425890298aed601595a70AB815c96711a31Bc65
     }
        
        
    function stake(uint _amount) external {
        require(_amount > 0, "amount is <= 0");
        //require(balanceOf(msg.sender) >= _amount, "balance >= amount");
        emit Staked(msg.sender, _amount);
        bool success = USDC.transferFrom(msg.sender, address(this), _amount);
        if (!success) {
            revert TransferFailed();
        }
         
        // (staked[msg.sender] > 0) {
        //    claim();
        //}
        stakedFromTS[msg.sender] = block.timestamp;
        staked[msg.sender] += _amount;
    }

    function unstake(uint _amount) external {
        require(_amount > 0, "amount is <= 0");
        require(staked[msg.sender] >= _amount, "amount is > staked");
        //claim();
        staked[msg.sender] -= _amount;
        emit WithdrewStake(msg.sender, _amount);
        bool success = USDC.transfer(msg.sender, _amount);
         if (!success) {
            revert TransferFailed();
        }
        

    }

    function claim() external {
        require(staked[msg.sender] > 0, "staked is <= 0");
        //uint secondsStaked = block.timestamp - stakedFromTS[msg.sender];
        require(block.timestamp >= stakedFromTS[msg.sender] + 3.154e7, "Cannot claim rewards yet");
        uint rewards = staked[msg.sender].mul(10).div(25) /* secondsStaked / 3.154e7;*/
        bool success = USDC.transfer(msg.sender,rewards);
        if (!success) {
            revert TransferFailed();
        }
         
        stakedFromTS[msg.sender] = block.timestamp;
    }

}



```

**Comment by jamesbachini** [comment]
The error is on line 64 where you just missed out a semi-colon at the end of the line ;

unstake will withdraw both the yield and collateral

**Comment by nzarambaelisa** [comment]
so, the function you said of stakeAll() in your website, that combines the rewards and the amount staked is not needed? and about the semi colon, i've now added it but the claim() addition in the unstake function is still throwing an error in remix

**Comment by jamesbachini** [comment]
What does the error say? I think you should look into doing some testing with hardhat before deploying anything. Get the code compiled and then write some unit and in system tests to ensure it does what you want and you have the functions you need.

**Comment by jamesbachini** [comment]
What does the error say? I think you should look into doing some testing with hardhat before deploying anything. Get the code compiled and then write some unit and in system tests to ensure it does what you want and you have the functions you need.

**Comment by nzarambaelisa** [comment]
sir, is it ok to make the claim function nonreeentrant in fixed rate contract? for it, it's a public function, it's not external as the stake and unstake functions
```solidity
function claim() public nonreentrant {}
```

**Comment by jamesbachini** [comment]
yes

**Comment by nzarambaelisa** [comment]
if there is no problem, can i see your unit test for the fixed rate contract?
