### ISSUE TITLE
final review

### ISSUE THREAD

**Issue by nzarambaelisa** [jamesbachini/Solidity-Snippets#2]

**Comment by jamesbachini** [comment]
Looks good, so the tokens will be locked for the year whenever the user stakes or claims. They can't remove them at any point within that year period. 

I would recommend doing some unit tests and do a thorough security review before deploying just to be sure it works as expected.

**Comment by nzarambaelisa** [comment]
thanks for the comment, now i understand

**Comment by nzarambaelisa** [comment]
![fixed](https://user-images.githubusercontent.com/97243123/218784948-dd54d6d6-0c3e-4c4b-b595-d8c6ffdf0b79.png)

sir, i can get this function that you said on your website? please

**Comment by jamesbachini** [comment]
function restakeAll() external nonReentrant {
    uint amount = staked[msg.sender];
    unstake(amount);
    uint balance = token.balanceOf(msg.sender);
    stake(balance);
}

// Something like this? Note this is untested so may or may not work, test accordingly.

**Comment by nzarambaelisa** [comment]
if i can ask? is it possible to make a function that links the unstake and the claim function so that they can be called in one function

**Comment by jamesbachini** [comment]
Unstake already calls the claim function

**Comment by nzarambaelisa** [comment]
hello sir,
Question? say i want to lock a certain address from withdrawing, are these the right functionalities of locking and unlocking certain staker's funds of choice? i mean, can i use it in the above fixedrate smart contract to lock a staker's funds?
```solidity
function lockFunds(address _staker, address _lockAddress, uint _amount) external onlyOwner {
    require(_staker != address(0), "staker address is 0");
    require(_lockAddress != address(0), "lock address is 0");
    require(_amount > 0, "amount is <= 0");
    require(_amount <= staked[_staker], "Insufficient staked balance");

    lockedFunds[_staker][_lockAddress] += _amount; // add the locked funds for this staker and lockAddress
    staked[_staker] -= _amount; // deduct the locked amount from staked balance of the staker

function unlockFunds(address _staker, address _lockAddress, uint _amount) external onlyOwner {
    require(_staker != address(0), "staker address is 0");
    require(_lockAddress != address(0), "lock address is 0");
    require(_amount > 0, "amount is <= 0");
    require(_amount <= lockedFunds[_staker][_lockAddress], "Insufficient locked funds balance");

    lockedFunds[_staker][_lockAddress] -= _amount; // deduct the unlocked amount from locked funds balance of the staker
    staked[_staker] += _amount; // add the unlocked amount to staked balance of the staker

    emit UnlockedFunds(_staker, _lockAddress, _amount);
```

**Comment by jamesbachini** [comment]
Looks like there might be a few issues such as emitting event for locking? You would need to do some unit testing to check it works as expected as very hard to tell without thorough testing.

**Comment by nzarambaelisa** [comment]
hello sir,
sir for unit testing, i am still learning. solidity is the first language, i learnt. i am not a pro in nodejs and javascript but i am learning because im using hardhat for development that's why im trying to first not present my ideas wrong. like here im trying to include a condition in my code where i added a function in my contract that is only called by the owner of the contract that  lock a certain address of choice from withdrawing funds. QUESTION? does the code make sense?
first i created a variable
```solidity
mapping(address => bool) public locked;
```
then i made a function that sets a particular address to true 
```solidity
function lockAccount(address _staker) external onlyOwner {
        require(_staker != address(0), "invalid address");
        require(_staker != owner, "cannot lock owner account");
        require(locked[_account] != true, "account is already in requested lock state");

        locked[_staker] = true;
    }
```
then i created a modifier that checks for true otherwise false so that other addresses when they call withdraw, they mark as false because in the unstake function it is said to require ``` require(locked[msg.sender] = false); ```
```solidity
modifier situation() {
        locked[msg.sender] = lockAccount(msg.sender) ? true : false;
        _;
    } 

function Unstake(uint _amount) external situation nonReentrant {
        require(_amount > 0, "amount is <= 0");
        require(staked[msg.sender] >= _amount, "amount is > staked");
        require(locked[msg.sender] = false);
        claim();
        staked[msg.sender] -= _amount;
        emit Unstake(msg.sender, _amount);
        bool success = token.transfer(msg.sender, _amount);
         if (!success) {
            revert Fixedstaking__TransferFailed();
        }
        

    }

```

**Comment by jamesbachini** [comment]
I'm really not sure, sorry. You can do some testing in remix too to make sure it works as you intend

**Comment by nzarambaelisa** [comment]
sir, compiling the fixed staking contract is showing an error on claim() function which is called in the stake and unstake function. it is said "undeclared identifier. "claim" is not (or not yet) visible at this point. what do i do?

**Comment by nzarambaelisa** [comment]
sir, i made the claim function nonreentrant and when i was testing the unstake(which is also nonreentrant) to see if it calls the claim function, i got an error of nonreentrant. do i have to omit nonreentrant in the claim function even though it is called externally? the test was passing when i removed nonreentrant on either the unstake or the claim function

**Comment by jamesbachini** [comment]
Sounds like an issue with the application of the reentrancy module. Did you label the internal function correctly?

**Comment by nzarambaelisa** [comment]
Sir, looking at my code above, how should have labeled the internal function correctly?

**Comment by nzarambaelisa** [comment]
Sir, looking at my code above, how should i have labeled the internal function correctly?

**Comment by nzarambaelisa** [comment]
Sir, looking at my code above, how should i have labeled the internal function correctly?

**Comment by jamesbachini** [comment]
I don't know, the code doesn't even compile. You are missing a semi-colon on line 12 ;

IERC20 public token;

There's likely other issues as well but I can't fix it for you, sorry.

I'd recommend fixing any bugs in remix and then spending some time unit testing in hardhat or foundry.

Sorry I can't be of more help here.

**Comment by nzarambaelisa** [comment]
sir, the problem i have here is that public nonreentrant function when called inside an external nonreentrant function, it results into an error reentrant call. i want to know how to solve that
