### ISSUE TITLE
view function

### ISSUE THREAD

**Issue by kidimorg** [jamesbachini/Solidity-Snippets#3]
hello,
i'm trying to make view function for the rewards of stakers for the frontend in the fixedratestaking contract, but i'm not seeing change on the frontend, is my code correct? here is the two code
your fixedratestaking contract
```solidity
// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract FixedStaking is ERC20 {
    mapping(address => uint) public staked;
    mapping(address => uint) private stakedFromTS;
    
    constructor() ERC20("Fixed Staking", "FIX") {
        _mint(msg.sender,1000000000000000000);
    }

    function stake(uint amount) external {
        require(amount > 0, "amount is <= 0");
        require(balanceOf(msg.sender) >= amount, "balance is <= amount");
        _transfer(msg.sender, address(this), amount);
        if (staked[msg.sender] > 0) {
            claim();
        }
        stakedFromTS[msg.sender] = block.timestamp;
        staked[msg.sender] += amount;
    }

    function unstake(uint amount) external {
        require(amount > 0, "amount is <= 0");
        require(staked[msg.sender] >= amount, "amount is > staked");
        claim();
        staked[msg.sender] -= amount;
        _transfer(address(this), msg.sender, amount);
    }

    function claim() public {
        require(staked[msg.sender] > 0, "staked is <= 0");
        uint secondsStaked = block.timestamp - stakedFromTS[msg.sender];
        uint rewards = staked[msg.sender] * secondsStaked / 3.154e7;
        _mint(msg.sender,rewards);
        stakedFromTS[msg.sender] = block.timestamp;
    }
}
```
here is my view function for the rewards of stakers in the contract
```solidty
function getRewards(address account) public view returns (uint256) {
        uint256 secondsStaked = block.timestamp - stakedFromTS[account];
        uint256 rewards = (staked[account]) * secondsStaked /3.154e7 ;
        return rewards;
    }
```

**Comment by jamesbachini** [comment]
Yes your function looks fine. Could try calling the function manually via a unit test to check it works as expected

**Comment by kidimorg** [comment]
yes via unit test, it works, but when viewed on the frontend, it does not show the rewards accumulated. it stays on 0

**Comment by jamesbachini** [comment]
Must be an issue with the frontend. Cache perhaps?

**Comment by kidimorg** [comment]
how cache? i did write the frontend code correct as the other view functions. and i did change returns to check where the problem was and when interchangeably the view function had block.timestamp or stakedFromTS[account] in it, return wasn't showing on the frontend and when (staked[account]) was the return, changes were shown

**Comment by jamesbachini** [comment]
If it works in a unit test then the issue can't be with the smart contract because if it was the unit tests wouldn't pass. There's not much to go on to try and help debug the issue, sorry. Maybe try console logging the outputs on the front-end?

**Comment by kidimorg** [comment]
yes, i did console.log on the frontend, but still the console was showing 0. is there another way of reading the rewards of stakers? i'm wondering why unit test is showing the function is working well, but the frontend doesn't show the rewards. might it be because the getrewards function isn't reading directly from the claim function because there is a source that did give me that as a possibilty?

**Comment by jamesbachini** [comment]
You could try it on a block explorer

**Comment by kidimorg** [comment]
you mean trying with testnet and see if see change

**Comment by jamesbachini** [comment]
Yes try and isolate the issue

**Comment by kidimorg** [comment]
James, i have used hardhat to deploy and for the frontend, and i'm seeing that with hardhat, it mines a new block when a transaction happpens, isn't it the reason, i can't see block.timestamp? because there are no constant blocks being mined

**Comment by jamesbachini** [comment]
Are you deploying it locally or to a external network? Maybe check that your frontend can see the recently deployed contract just to verify the networks are set up correctly

**Comment by kidimorg** [comment]
i was deploying locally. thank you for your help James. at first, i thought the problem was in the backend, but after your info i did my research and i got to know that with the hardhat node, blocks aren't mined regularly instead the mine happens when transaction is made that's why my result was 0.
